const sequelize = require('../config/connection');
const { User, Post, Comment } = require('../models'); // ~/models/index.js

const userData = require('./users.json');
const postData = require('./posts.json');
const commentData = require('./comments.json');


const seedDatabase = async () => {
    await sequelize.sync({force: true}); // force:true = drop all tables and restart from scratch

    await User.bulkCreate(userData, {
        individualHooks: true,
        returning: true, // append RETURNING <model columns> to get back all defined values (https://sequelize.org/master/class/lib/model.js~Model.html#static-method-bulkCreate) <--- to get autogenerated IDs
    });
    console.log('----------------------- USERS SEEDED -----------------------');

    await Post.bulkCreate(postData);
    console.log('----------------------- POSTS SEEDED -----------------------');

    await Comment.bulkCreate(commentData);
    console.log('----------------------- COMMENTS SEEDED -----------------------');
    
    process.exit(0);
}

seedDatabase();